Add threaded serial port
AllenNeuralDynamics/pyharp pull request #4
Opened 2024-10-30 23:26 UTC by patricklatimer

Here's what I put together for handling events from harp devices. I haven't really gone through and cleaned it up so it might be a little messy in parts, but I tested it a little with the environment sensor and it seems to work.

2025-01-08 17:05 UTC, mah1329 commented on pyharp/device.py
> +        reg_value &= ~0x03  # mask off old mode.
In C I'm used to #define's that clearly state what the mask or shift is like, #define OLD_MODE 0x03, saves a comment and I think reads better. is there a good analogue in Python? Same thing with the bit shifts below.

2025-01-08 17:56 UTC, patricklatimer commented on pyharp/device.py
> +        reg_value &= ~0x03  # mask off old mode.
There's certainly room for improvement here and in other places to make it a little clearer and more maintainable. I kept my changes isolated to the harp_serial portion for this PR, but it looks like my formatter had some fun with other code that I didn't intend to include for review.

2025-02-07 23:44 UTC, Poofjunior requested changes
Overall, really huge addition for the long term. Great job!

Since this project is a fork, can we undo the linter changes so that we can ultimately submit an upstream PR with the minimum changes for the main repo folks to approve? That way they can ultimately get these onto PyPI for us.

2025-02-07 23:44 UTC, Poofjunior commented on pyharp/device.py
> +    def get_events(self) -> list[ReplyHarpMessage]:
This looks great! Let's add:
1. a docstring
2. another function called `event_count()` or `num_events()` that returns the number of event messages in the queue.

2025-02-07 23:44 UTC, Poofjunior commented on tests/test_device.py
> +    while True:
You have a nice `get_events()` function already written. Can we use that here in this example instead of accessing the underlying object?

2025-02-13 00:40 UTC, Poofjunior commented
@patricklatimer for 3.8 compatibility we will need:
````python
from __future__ import annotations # enable subscriptable type hints for lists.
````
at the top of device.py and any other files that use type hints where you subscript `list` instead of using `Typing.List`

2025-02-13 00:44 UTC, patricklatimer commented
> @patricklatimer for 3.8 compatibility we will need:
> 
> ```python
> from __future__ import annotations # enable subscriptable type hints for lists.
> ```
> 
> at the top of device.py and any other files that use type hints where you subscript `list` instead of using `Typing.List`

2025-02-13 00:45 UTC, patricklatimer commented
^ whoops

Good catch, maybe I should just use Typing.List

2025-02-13 00:58 UTC, Poofjunior approved these changes

2025-02-13 00:58 UTC, merged